# Generated by Django 5.0.14 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_cliente_producto_stook_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stook',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('CERRADO', 'Cerrado')], default='CREADO', max_length=10),
        ),
    ]
