# Generated by Django 5.2.13 on 2026-04-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_pedido_productos_pedidoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='productos',
            new_name='producto',
        ),
    ]
